### ISSUE TITLE
ModuleNoFoundError: No Module named 'matplitlob'

### ISSUE THREAD

**Issue by anujblink** [deadlocker/fantasy-premier-league-2019#1]
![image](https://user-images.githubusercontent.com/50903319/62522171-17653c00-b86c-11e9-91ff-ee9b2500d607.png)

Getting this error

**Comment by deadlocker** [comment]
Hi anujblink,
looks like you are using windows.
You can install matplotlib module from **https://matplotlib.org/3.1.0/users/installing.html**.
Additionally, you also need other modules to be enabled/installed on your system that the program requires. 
Deadlocker
